<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>BetterBackup</AssemblyName>
    <RootNamespace>BackupPlacement</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="System.Windows.Forms" />
    <Reference Include="Microsoft.CSharp" />

    <Reference Include="RagePluginHookSDK">
      <HintPath>References\RagePluginHookSDK.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="LSPD First Response">
      <HintPath>References\LSPD First Response.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="PolicingRedefined">
      <HintPath>References\PolicingRedefined.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>

</Project>